apiVersion: v1
kind: Service
metadata:
  name: {{ include "brainbox.fullname" . }}
  labels: {{- include "brainbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.brainbox.service.type }}
  ports:
    - port: {{ .Values.brainbox.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "brainbox.selectorLabels" . | nindent 4 }}