{{- if and .Values.redis.enabled .Values.redis.auth.enabled .Values.redis.auth.password (not .Values.redis.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "brainbox.fullname" . }}-redis
  labels:
    {{- include "brainbox.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.auth.secretKeys.redisPasswordKey }}: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }} 